### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by stmax82** [philferriere/dlwin#1]
**Python 2.7**

Is Python 2.7 really necessary? I install Theano+Keras pretty much the same way as you do (without OpenBLAS and cuDNN though), but I use Anaconda with Python 3 and everything works fine.

**MinGW**

The installation of MinGW can be simplified, because there's a conda package for it. Just conda install mingw.

**pip + git**

Instead of git clone and python setup.py you can just use a single line of pip to install Theano and Keras:

pip install git+https://github.com/Theano/Theano.git@rel-0.8.2
pip install git+https://github.com/fchollet/keras.git@1.0.5

Thanks for the guide!

**Comment by philferriere** [comment]
Great notes. Thanks for the feedback!

**Comment by alexander-rakhlin** [comment]
@stmax82, do you fall back to Python 3.4 environment like I do? I was unable to install 
`conda install libpython`
with 3.5

**Comment by stmax82** [comment]
@alexander-rakhlin most of my Python envs are a bit older and thus 3.4 by default - but you're right, I just tried to create a 3.5 environment and the libpython conda package doesn't seem to be available for 3.5 (yet?).

I'm not sure how the conda package maintenance process works and who's responsible for updating packages?

**Comment by philferriere** [comment]
Closing all comments related to Keras1.0.5 + Theano0.8.2 + VS2013 + CUDA7.5 + cuDNN5.0 setup.
Switching to Keras1.1.0 + Theano0.8.2 + VS2015 + CUDA8.0 + cuDNN5.1 setup.
