### ISSUE TITLE
Openblas Dependency

### ISSUE THREAD

**Issue by Marsrocky** [philferriere/dlwin#10]
When I completed the process, the test python program 'mnist_cnn.py‘ worked well in GPU0 but failed with CPU only mode. In this case, the problem lies in the incorrect configuration of OPENBLAS.
### If we wanna use cpu-only keras, the openblas should be configured as follows:
1. Download the precompiled libopenblas.dll from [openblas/v0.2.14/](http://sourceforge.net/projects/openblas/files/v0.2.14/) 
2. Download [mingw64_dll.zip](http://sourceforge.net/projects/openblas/files/v0.2.14/mingw64_dll.zip/download) as well
   Mine is OpenBLAS-v0.2.14-Win64-int32.zip.

Extract the dll in bin folder of the zip to C:\openblas. Also extract all dlls in mingw64 to the same location

Set **blas.ldflags=-LC:\openblas -lopenblas** in THEANO_FLAGS (or .theanorc.txt)

**Comment by Marsrocky** [comment]
My configuration is Win10 x64, CUDA 8.0, python 2.7.12, theano0.8.2, keras 1.1.0.

Thanks for your help!

**Comment by apacha** [comment]
This was a [known bug](https://github.com/Theano/Theano/issues/5653) that has been fixed in newer versions of Theano. Please let us know, if this is still an issue and I will re-open it.
