### ISSUE TITLE
How to update Keras 1.1.1

### ISSUE THREAD

**Issue by toqitahamid** [philferriere/dlwin#12]
New version of Keras 1.1.1 has arrived at github. How do I update Keras?

**Comment by apacha** [comment]
See the [updated version](https://github.com/apacha/dlwin) which is currently being reviewed to use the newest versions of Keras and Theano.

**Comment by apacha** [comment]
Basically you can use `pip install keras==2.0.4` to install a specific version (say 2.0.4) of keras. If you have installed keras before, you can use `pip uninstall keras` to remove it first.
