### ISSUE TITLE
Is it possible to uninstall all the software installed with VS 2015 Community Edition at the end? 

### ISSUE THREAD

**Issue by andreisland** [philferriere/dlwin#14]
Hello, 
as by title I wonder if it is possible to uninstall the very large VS 2015 packages, once Theano and everything is installed and performs properly. 
Thank you.

**Comment by apacha** [comment]
No, the C++ compiler from Visual Studio will be used for running Theano (basically whenever you starts a script, it will compile optimized operations for your network), so it can not be uninstalled.
