### ISSUE TITLE
TheanoConfigWarning: Config key 'THEANO_FLAGS_GPU' has no value, ignoring it

### ISSUE THREAD

**Issue by Saghar-Hosseini** [philferriere/dlwin#17]
Hello,
Thanks for the clear and helpful instruction. I'm still having problems running Theano on GPU and receive this error when I run the test file:

**> ...\Anaconda2\lib\site-packages\theano\configdefaults.py:16: TheanoConfigWarning: Config key 'THEANO_FLAGS_GPU' has no value, ignoring it
>   from theano.configparser import (AddConfigVar, BoolParam, ConfigParam, EnumStr,
> [Elemwise{exp,no_inplace}(<TensorType(float64, vector)>)]
> Looping 1000 times took 12.192000 seconds
> Result is [ 1.23178032  1.61879341  1.52278065 ...,  2.20771815  2.29967753
>   1.62323285]
> Used the cpu**

Thanks!

**Comment by apacha** [comment]
Can you post a screenshot of your environment settings?

**Comment by singhay** [comment]
I am facing the same issue, I think it has something to do with `blas.ldflags=-LC:/toolkits/OpenBLAS-v0.2.19-Win64-int32/bin` since on typing $THEANO_FLAGS_CPU/GPU is get 
`$ $THEANO_FLAGS_GPU
-bash: floatX=float32,device=gpu,dnn.enabled=False,lib.cnmem=0.8,blas.ldflags=-LC:/toolkits/OpenBLAS-v0.2.19-Win64-int32/bin: No such file or directory`

**Comment by philferriere** [comment]
Please let me know if you still have issues with the new Theano flags for libgpuarray.

**Comment by JeffreyYeTHU** [comment]
I have the same issue too. 

I am following the instruction, and everything seems OK.

The sysenvs also seem fine:

>   (C:\ProgramData\Anaconda3) c:\Users\yejian\dlwin36>set KERAS_BACKEND=theano
(C:\ProgramData\Anaconda3) c:\Users\yejian\dlwin36>set | findstr /i theano
KERAS_BACKEND=theano
THEANO_FLAGS=float32,device=cuda0,optimizer_including=cudnn,gpuarray.preallocate=0.8,dnn.conv.algo_bwd_filter=deterministic,dnn.conv.algo_bwd_data=deterministic,dnn.include_path=e:/toolkits.win/cuda-8.0.61/include,dnn.library_path=e:/toolkits.win/cuda-8.0.61/lib/x64
THEANO_FLAGS_CPU=float32,device=cpu
THEANO_FLAGS_GPU=floatX=float32,device=cuda0,dnn.enabled=False,gpuarray.preallocate=0.8
THEANO_FLAGS_GPU_DNN=floatX=float32,device=cuda0,optimizer_including=cudnn,gpuarray.preallocate=0.8,dnn.conv.algo_bwd_filter=deterministic,dnn.conv.algo_bwd_data=deterministic,dnn.include_path=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include,dnn.library_path=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64

But when I run the cpu_gpu_test.py, I get:

> C:\ProgramData\Anaconda3) c:\Users\yejian\dlwin36>set THEANO_FLAGS=%THEANO_FLAGS_CPU%
(C:\ProgramData\Anaconda3) c:\Users\yejian\dlwin36>python cpu_gpu_test.py
C:\ProgramData\Anaconda3\lib\site-packages\theano\configdefaults.py:17: **TheanoConfigWarning: Config key 'float32' has no value, ignoring it**
  from theano.configparser import (AddConfigVar, BoolParam, ConfigParam, EnumStr,
[Elemwise{exp,no_inplace}(<TensorType(float64, vector)>)]
                                                               Looping 1000 times took 11.881007 seconds
Result is [ 1.23178032  1.61879341  1.52278065 ...,  2.20771815  2.29967753
  1.62323285]
Used the cpu

Then, I open my jupyter nootbook, bu just import the theano, I get the same error.

`import theano`

> C:\ProgramData\Anaconda3\lib\site-packages\theano\configdefaults.py:17: **TheanoConfigWarning: Config key 'float32' has no value, ignoring it**
  from theano.configparser import (AddConfigVar, BoolParam, ConfigParam, EnumStr,
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\theano\gpuarray\__init__.py", line 164, in <module>
    use(config.device)
  File "C:\ProgramData\Anaconda3\lib\site-packages\theano\gpuarray\__init__.py", line 151, in use
    init_dev(device)
  File "C:\ProgramData\Anaconda3\lib\site-packages\theano\gpuarray\__init__.py", line 60, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu\gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
  File "pygpu\gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
  File "pygpu\gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
pygpu.gpuarray.GpuArrayException: Error loading library: 0

Do you have any suggestions?

Thanks!

**Comment by philferriere** [comment]
This is a README.md typo. Use:
`THEANO_FLAGS_CPU=floatX=float32,device=cpu`
instead of
`THEANO_FLAGS_CPU=float32,device=cpu`

**Comment by JeffreyYeTHU** [comment]
@philferriere  Thx, problem solved!
