### ISSUE TITLE
Problems with theano and mingw

### ISSUE THREAD

**Issue by rodrigocesar** [philferriere/dlwin#19]
Theano is not working.

===============================
Problem occurred during compilation with the command line below:
C:\toolkits\mingw-w64-6.3.0\mingw64\bin\g++.exe -shared -g -march=skylake -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mrtm -mhle -mrdrnd -mf16c -mfsgsbase -mrdseed -mprfchw -madx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mclflushopt -mxsavec -mxsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-mwaitx -mno-clzero -mno-pku --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=6144 -mtune=skylake -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -IC:\toolkits\lib\site-packages\numpy\core\include -IC:\toolkits\include -IC:\toolkits\lib\site-packages\theano\gof -o C:\Users\Rodrigo\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\Rodrigo\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-64\lazylinker_ext\mod.cpp -LC:\toolkits\libs -LC:\toolkits -lpython27
In file included from C:/toolkits/mingw-w64-6.3.0/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/math.h:36:0,
                 from C:\toolkits\include/pyport.h:325,
                 from C:\toolkits\include/Python.h:58,
                 from C:\Users\Rodrigo\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-64\lazylinker_ext\mod.cpp:1:
C:/toolkits/mingw-w64-6.3.0/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/cmath:1157:11: error: '::hypot' has not been declared
   using ::hypot;
           ^~~~~

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\toolkits\lib\site-packages\theano\__init__.py", line 63, in <module>
    from theano.compile import (
  File "C:\toolkits\lib\site-packages\theano\compile\__init__.py", line 9, in <module>
    from theano.compile.function_module import *
  File "C:\toolkits\lib\site-packages\theano\compile\function_module.py", line 22, in <module>
    import theano.compile.mode
  File "C:\toolkits\lib\site-packages\theano\compile\mode.py", line 12, in <module>
    import theano.gof.vm
  File "C:\toolkits\lib\site-packages\theano\gof\vm.py", line 638, in <module>
    from . import lazylinker_c
  File "C:\toolkits\lib\site-packages\theano\gof\lazylinker_c.py", line 126, in <module>
    preargs=args)
  File "C:\toolkits\lib\site-packages\theano\gof\cmodule.py", line 2204, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): In file included from C:/toolkits/mingw-w64-6.3.0/mingw64/lib/gcc/x86_6.                  from C:\Users\Rodrigo\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94. C:/toolkits/mingw-w64-6.3.0/mingw64/lib/gcc/x86_64-w64-mingw32/6.3.0/include/c++/cmath:1157:11: error: '::hypot' has n.            ^~~~~;
>>>

**Comment by apacha** [comment]
The version of MingW you are using is known not to work (I've tried by myself), so the tutorial referred to version 5.4.0. Please use that version instead of 6.3.0.

**Comment by apacha** [comment]
As mentioned in #7, you probably don't need MinGW at all.

**Comment by rodrigocesar** [comment]
I am replacing Ming.


Thanks for your help!

Rodrigo.
