### ISSUE TITLE
VS2013 link rot

### ISSUE THREAD

**Issue by valtron** [philferriere/dlwin#2]
It's no longer possible to link directly to VS2013. Instead, one has to:
1. Go to https://www.visualstudio.com/vs/older-downloads/
2. "Already a member? Sign in"
3. Use http://bugmenot.com/view/microsoftonline.com if you don't have an account
4. Go to https://my.visualstudio.com/downloads
5. Ctrl+F "Visual Studio Express 2013 for Windows with Update 4"

**Comment by philferriere** [comment]
Thanks for the update, valtron. The information you provided has been added to the README file.
