### ISSUE TITLE
conda install theano

### ISSUE THREAD

**Issue by stmax82** [philferriere/dlwin#20]
There's a theano package for conda since a while. Makes installation much easier because it already comes with all the dependencies - like gcc and libpython.

How I install theano lately:

conda create -p pyenv python=3.5
conda install -p pyenv theano
activate pyenv
pip install keras

done 👍

**Comment by stmax82** [comment]
... and there's pip install tensorflow since a while too. I haven't tried that yet though.

**Comment by alexander-rakhlin** [comment]
Hey stmax82! Have you tried to run this theano installation on CPU, as opposed to GPU?

On CPU I get errors like this, GPU is okay:

>   File "C:\Anaconda3\envs\pyenv\lib\site-packages\theano\gof\cmodule.py", line 2213, in compile_str
>     return dlimport(lib_filename)
>   File "C:\Anaconda3\envs\pyenv\lib\site-packages\theano\gof\cmodule.py", line 299, in dlimport
>     rval = __import__(module_name, {}, {}, [module_name])
> ImportError: DLL load failed: The specified module could not be found.

**Comment by alexander-rakhlin** [comment]
update:

It appears **openblas** is the reason. When I suppress this line in .theanorc, it runs on CPU.

> [blas]
> ldflags=-LC:\\openblas -lopenblas

**Comment by stmax82** [comment]
Looks like someone already reported this problem on theano's issue tracker two days ago:
https://github.com/Theano/Theano/issues/5653

A few weeks ago (short before I posted this) I did a few CPU vs GPU vs cuDNN benchmarks of CNNs and it worked flawlessly on the CPU. The reason probably is that I do not use OpenBLAS.

**Comment by alexander-rakhlin** [comment]
Thanks! I am not alone then

And one of your [links](https://stackoverflow.com/questions/34508431/installing-theano-on-windows-dll-load-failed) helped: you only need to add openblas directory to system Path

**Comment by alexander-rakhlin** [comment]
Interestingly, with openblas check_blas.py runs 4 times slower. In the past, for other versions of Python/theano openblas significantly improved over default settings.

without openblas:
Total execution time: 6.90s on CPU (with direct Theano binding to blas).

openblas:
Total execution time: 32.58s on CPU (with direct Theano binding to blas).

**Comment by lamblin** [comment]
Conda now ships with MKL by default, which Theano should be able to use (at least if NumPy is installed through conda), and which may be faster than OpenBlas.

**Comment by apacha** [comment]
As Conda now ships with MKL (or at least it can be installed using `conda install mkl-service`), should we remove OpenBLAS entirely from the tutorial? What do you think @philferriere ?

**Comment by apacha** [comment]
Regarding BLAS and OpenBLAS I found this answer on [Stackoverflow](https://stackoverflow.com/a/19350234/448357) that allows to display which BLAS version is installed and used by numpy/scipy:
```python
import numpy
numpy.__config__.show()
```

For my machine, I get this
```
lapack_mkl_info:
    include_dirs = ['C:/Programming/Anaconda3-4.2.0\\Library\\include']
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    library_dirs = ['C:/Programming/Anaconda3-4.2.0\\Library\\lib']
openblas_lapack_info:
  NOT AVAILABLE
lapack_opt_info:
    include_dirs = ['C:/Programming/Anaconda3-4.2.0\\Library\\include']
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    library_dirs = ['C:/Programming/Anaconda3-4.2.0\\Library\\lib']
blas_opt_info:
    include_dirs = ['C:/Programming/Anaconda3-4.2.0\\Library\\include']
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    library_dirs = ['C:/Programming/Anaconda3-4.2.0\\Library\\lib']
blas_mkl_info:
    include_dirs = ['C:/Programming/Anaconda3-4.2.0\\Library\\include']
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    library_dirs = ['C:/Programming/Anaconda3-4.2.0\\Library\\lib']
```
which indicates that the optimized Intel MKL library is being used. That might have been the case at @alexander-rakhlin as @lamblin already suggested. @alexander-rakhlin, could you confirm this?

**Comment by alexander-rakhlin** [comment]
My output is the same
```
np.__config__.show()
lapack_mkl_info:
    include_dirs = ['C:/Anaconda3\\Library\\include']
    library_dirs = ['C:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
blas_mkl_info:
    include_dirs = ['C:/Anaconda3\\Library\\include']
    library_dirs = ['C:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
blas_opt_info:
    include_dirs = ['C:/Anaconda3\\Library\\include']
    library_dirs = ['C:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
openblas_lapack_info:
  NOT AVAILABLE
lapack_opt_info:
    include_dirs = ['C:/Anaconda3\\Library\\include']
    library_dirs = ['C:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
```

**Comment by philferriere** [comment]
I'm all for it @apacha. Please make sure to also add the tiny snippet of code for the confg check you showed above to the README (and its output, so everyone can see what they can expect from it). Thanks much!

**Comment by philferriere** [comment]
Seems to work pretty well now, indeed.
