### ISSUE TITLE
Many thanks to the author. Everything works great!!!

### ISSUE THREAD

**Issue by WhiteSharkwww** [philferriere/dlwin#21]
I am a very long time (2 weeks) tried solve this problem. I could not. However, this manual helped me. Now everything works perfectly. Many thanks to the author. I used:
- Window 10
- Anaconda with python 3.5
- Tneano 0.9.0rc1 (I made: pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git)
- keras 1.2.2 (I made: pip install keras)

Everything is great!!! Thanks a lot, Phil!!!

**Comment by apacha** [comment]
Thanks, we will try to keep this tutorial updated.
