### ISSUE TITLE
Update flags for the next Theano release to use new cuda backend (instead of gpu backend)

### ISSUE THREAD

**Issue by apacha** [philferriere/dlwin#24]
As noticed when running Theano 0.9 and described in the [documentation](http://www.deeplearning.net/software/theano/tutorial/using_gpu.html#cuda) the GPU-Backend is deprecated and the Cuda-Backend should be used. When the next Theano version will be release (probably 0.10), the documentation should be updated to use the correct flags, including:

- `device=cuda` instead of `device=gpu`
- `config.gpuarray.preallocate` instead of `config.lib.cnmem`

I've briefly tested those two flags, but then I ended up getting other errors. The [official documentation](http://deeplearning.net/software/libgpuarray/installation.html) currently does not seem helpful.

**Comment by philferriere** [comment]
Done.
