### ISSUE TITLE
powershell, vs2015/2017

### ISSUE THREAD

**Issue by neutmute** [philferriere/dlwin#25]
Thanks for this detailed set of instructions.
There is a lot of old and now incorrect instructions trying to get this tech stack going on windows - yours is the most complete!

I'm trying to run through them now and have some suggestions. Happy to PR them once I get this all going.

1. Replace some manual steps with powershell where possibe.
eg: This is what I have for setting mingw paths. There are some other spots that can be scripted too

```
# Powershell - run elevated
Write-Host "Define the sysenv variable MINGW_HOME"
$mingwHome = "c:\toolkits\mingw-w64-5.4.0"
[Environment]::SetEnvironmentVariable( "MINGW_HOME", $mingwHome, "Machine")
Write-Host "Appending mingw bin's to PATH"
[Environment]::SetEnvironmentVariable( "Path", $env:Path + ";$mingwHome\mingw64\bin", "Machine")
```

2. VS2015 Community is no longer available for download except for MSDN subscribers. I thought I would try my luck with VS2017.
If so, could we split the VS2015/VS2017 instructions into separate readme's (`vs2015.md`, `vs2017.md`) with a pointer from the main readme.md.
The main readme.md could have something like 
```
Stable: Install Visual Studio 2015 (hyperlinked)
Experimental: Install Visual Studio 2017 (hyperlinked)
```
Splitting the instructions down allows a set of updated instructions to be in the pipeline that may not always be the easy happy path but available for those who want to try and allows you to get feedback / PRs for refinement.

fyi I'm coming at this as a student of fast.ai
Thoughts?

**Comment by philferriere** [comment]
Thank you for offering to help, @neutmute.

1/ Too few people are familiar with Powershell. That being said, if you've written a script that can run all the steps, I'll gladly add it to an appendix section of the README. PR welcome.

2/ As long as VS 2017 isn't listed [here](http://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#system-requirements), I highly recommend that you stay away from it (for this tutorial, that is).

Best, -- Phil

**Comment by neutmute** [comment]
1) well i just have some scripts i have used that can replace some verbiage instructions on setting env vars so far. 
it would be better to have it inline rather than as an appendix i think. 
i could convert it to batch file using `setx` say? powershell is a bit more powerful as you would know - but understand you are writing for a wider audience. would a batch file version acceptable for inline replacement? can PR a sample first if that helps discuss the style change 

2) ah, thanks, that has saved me going down a false path. will roll to back vs2015 for my ongoing setup

**Comment by apacha** [comment]
Just my two cent on the issue: I think having a script to set environment variables does not hurt anyone and  with the newest updates to Windows 10, adding Environment variables has become yet more tedious, because they hid it one more menu down the line to find. I'd welcome a script that can automate what otherwise I would have to do by hand. People can still do it manually, but adding the appropriate commands inline could speed up the process.

Regarding VS2017: I've installed VS2017 first and it did not work, so I had to install VS2015 too (unfortunately). As Microsoft has now switched to 2017 on their homepage, we should include the link to https://www.visualstudio.com/vs/older-downloads/ for people to find it.

**Comment by neutmute** [comment]
Inclined to agree with apacha here. Anyone doing this level of setup can be reasonably expected to know how to execute powershell (maybe this is my normalcy bias as a c# dev?)

It leaves less room for error in reproducing the steps required -eg: current instructions indicate you might be able to use variable expansion in PATH:

`Add%CUDA_PATH%\libnvvp and %CUDA_PATH%\bin to PATH`

but this isn't possible and user needs to understand that when setting their own values manually.
Replacing with a powershell script means it is succinct and less error prone. It would be commented too to explain the intent.

Happy to roll with whatever you guys decide though of course

**Comment by neutmute** [comment]
I just did the BLAS/Theano flags part. I think this would be much improved with Powershell to detect whether user was using Blas or not

```
# Powershell
# Depending on whether OpenBLAS or MKL-Service was used, set the correct flags

$cpuFlags = "floatX=float32,device=cpu,lib.cnmem=0.8"
$gpuFlags = "floatX=float32,device=gpu,lib.cnmem=0.8,dnn.enabled=False"
$blasFlags = ",blas.ldflags=-LC:/toolkits/openblas-0.2.19/bin -lopenblas"

if ($env:OPENBLAS_HOME){
    $cpuFlags = $cpuFlags + $blasFlags
    $gpuFlags = $gpuFlags + $blasFlags
}

# For easy swapping between CPU vs GPU
[Environment]::SetEnvironmentVariable("THEANO_FLAGS_CPU", $cpuFlags, "Machine")
[Environment]::SetEnvironmentVariable("THEANO_FLAGS_GPU", $gpuFlags, "Machine")

# This is the only one Theano cares about
[Environment]::SetEnvironmentVariable("THEANO_FLAGS", $gpuFlags, "Machine")

```
Convinced yet ? :)

**Comment by neutmute** [comment]
CuDNN setup.

```

# Powershell - CuDNN
# Depending on whether OpenBLAS or MKL-Service was used, set the correct flags

$gpuDnnFlags = "floatX=float32,device=gpu,optimizer_including=cudnn,lib.cnmem=0.8,dnn.conv.algo_bwd_filter=deterministic,dnn.conv.algo_bwd_data=deterministic"
$blasFlags = ",blas.ldflags=-LC:/toolkits/openblas-0.2.19/bin -lopenblas"

if ($env:OPENBLAS_HOME){
    $gpuDnnFlags = $gpuDnnFlags + $blasFlags
}

# For easy swapping between CPU vs GPU vs CuDNN
[Environment]::SetEnvironmentVariable("THEANO_FLAGS_GPU_DNN", "$gpuDnnFlags", "Machine")

# To enable CuDNN
[Environment]::SetEnvironmentVariable("THEANO_FLAGS", $gpuDnnFlags, "Machine")
```
