### ISSUE TITLE
If Visual Studios was already installed on the machine "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\um\x64" will be missing

### ISSUE THREAD

**Issue by KenHollandWHY** [philferriere/dlwin#26]
The solution is to: 
"To get this (C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10586.0\um\x64\WindowsApp.lib) file use the Windows Control Panel, go to Programs and Features and double click Microsoft Visual Studio Community 2015. Then select Customize (or "Adjust", I see "Anpassen" as I'm from Germany) and select Tools (1.2) and Windows 10 SDK (10.0.10586) under Development Tools for Universal Windows Apps under Windows and Web Development (again: translations may differ). Then hit UPDATE. If that doesn't work try Emulators for Windows 10 Mobile (10.0.10586) and/or Windows 10 SDK (10.0.10240) too"
https://github.com/Microsoft/FFmpegInterop/issues/48

thanks for the great guide!

**Comment by philferriere** [comment]
Thanks for the info!
