### ISSUE TITLE
Fix for "vcvars64.bat" error

### ISSUE THREAD

**Issue by valtron** [philferriere/dlwin#3]
If you get the error:

```
nvcc fatal   : Microsoft Visual Studio configuration file 'vcvars64.bat' could not be found
for installation at 'C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/../..'
```

The solution is:
1. Copy `$VS12/VC/bin/x86_amd64` to `$VS12/VC/bin/amd64`
2. Rename `$VS12/VC/bin/amd64/vcvarsx86_amd64.bat` to `vcvars64.bat`

**Comment by philferriere** [comment]
Closing all comments related to Keras1.0.5 + Theano0.8.2 + VS2013 + CUDA7.5 + cuDNN5.0 setup.
Switching to Keras1.1.0 + Theano0.8.2 + VS2015 + CUDA8.0 + cuDNN5.1 setup.

**Comment by ankitdx** [comment]
@valtron your solution worked perfectly for me :)

**Comment by ArnaudNorel95** [comment]
Hi could someone explain me what is $VS12 ? is it an abreviation of Microsoft Visual Studio 12.0 ?
for me I cant find x86_amd64 or amd64 in my VC\bin ...
But my path in my error is not exactly the same : 
`Microsoft Visual Studio configuration file 'vcvars64.bat' could not be found for installation at 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/SDK/ScopeCppSDK/VC/bin/../..'`

Could someone help me please ?

**Comment by apacha** [comment]
VS12 would correspond to Visual Studio 2013 (see https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#History) for the corresponding codes. Visual Studio 2019 now has VS16.

**Comment by SofieLovdal** [comment]
@ArnaudNorel95 I have the same issue as you. Did you manage to resolve it?
