### ISSUE TITLE
cuDNN 5.1 - August 10, 2016 build no longer available

### ISSUE THREAD

**Issue by neutmute** [philferriere/dlwin#30]
The docs specify to get `cuDNN Library for Windows10 dated August 10, 2016` but that doesn't seem to be available anymore...

https://developer.nvidia.com/rdp/cudnn-download
<img width="579" alt="cudnn" src="https://cloud.githubusercontent.com/assets/1303131/26528956/1d0e2952-43fa-11e7-9ec9-03c3b03e6d14.png">

I'm going to try `cuDNN v5.1 (Jan 20, 2017), for CUDA 8.0`...

**Comment by apacha** [comment]
True. I think we should just remove the date, as the newer cuDNN version should work as-well. It is more important that you pick the right version for your CUDA.

**Comment by philferriere** [comment]
Do not remove the date. I want to be very clear about the purpose of this repo: to provide you with a setup that DOES work, not a setup that SHOULD work. If you are going to change the date, only do it after you have actually tested it with the version that has the later date.

Can we please all (@apacha and @neutmute) agree on this?

**Comment by apacha** [comment]
Updated readme

**Comment by apacha** [comment]
I've tested it with the newest version and it worked. And in this specific case, the older build is actually no longer available for download. But otherwise I totally agree with you @philferriere, that the instructions should only use tested and working versions instead of versions that "should" work.

**Comment by neutmute** [comment]
Agree @philferriere - this is precisely why your instructions are the best that I have found :)
Lots of out of date and misleading instructions out in the wild due to things moving so fast. eg: Keras 2 release in March - can no longer install `latest` and get same results as back in Feb.

**Comment by philferriere** [comment]
Thank you both!
