### ISSUE TITLE
Is there any reason for choosing 10.0.10240 over 10.0.10584?

### ISSUE THREAD

**Issue by darthdeus** [philferriere/dlwin#33]
Is there any reason why you're showing the older version of Windows 10 SDK in the install list?

![](http://i.imgur.com/2S4vGeS.png)

**Comment by philferriere** [comment]
My notes show that I couldn't get it to work with the 10586 point release. Unfortunately, I did not write down why. Sorry about that...

If you try it out, please let me know what you find out. If you can't get it to work, please remind me what errors or problems you encounter. But, if you get it to work, I'd like to know that too!

Thanks!
