### ISSUE TITLE
Simplified Keras + Tensorflow-GPU installation

### ISSUE THREAD

**Issue by apacha** [philferriere/dlwin#34]
Yesterday, upon setting up Keras+TF on another Windows 7 machine, I figured, that the TF+Keras installation can be simplified:

- No need of OpenBLAS
- No need of MinGW
- No need of setting up any Flags

but
- cuDNN is _mandatory_, or otherwise you will get a `DLL load failed` exception as described in [this questions on Stackoverflow](https://stackoverflow.com/questions/42011070/on-windows-running-import-tensorflow-generates-no-module-named-pywrap-tenso) - took me quite a while to figure out that cuDNN was the reason.

I wonder, if Visual Studio was required after all, but I didn't try it, since VS was already installed. Next time, I get the chance to set up a fresh system, I will try to only install the following:

- Anaconda 3 - 4.2.0
- Cuda 8.0
- cuDNN 5.1
- pip keras==2.0.4
- pip tensorflow-gpu==1.1.0

If someone get's the chance of trying this out, it would be great. We should also add an appropriate notice to the Tensorflow section, that cuDNN is mandatory.

**Comment by reppolice** [comment]
Compared to what was happening 6 months ago, it looks like this simple method works, so far! Windows Server 2016

**Comment by philferriere** [comment]
Indeed, it is simpler now with Keras 2.0.5, but in some cases (like with the CNTK backend) it can be still tricky. Thanks for the suggestion @apacha and showing it had potential @reppolice.

**Comment by apacha** [comment]
Great updates @philferriere! I was looking forward to this tutorial having all three backends. Recently talked to a guy from Microsoft, who said, that CNTK + Keras is now available and as simple as switching flags in the configuration.

**Comment by philferriere** [comment]
Thanks @apacha. Switching to the CNTK backend is indeed easy. The binary install of CUDA DLLs alongside CNTK, however, did compromise my Theano setup. Overall, everything is much simpler now, but you still have to be mindful of those side effects.

**Comment by apacha** [comment]
Just a short notice to this issue as I finally had a fresh PC to try it out: Visual Studio 2015 is *not* required when using only Keras + Tensorflow-GPU. This simplifies the installation even further.
