### ISSUE TITLE
Missing cudnn.h file?

### ISSUE THREAD

**Issue by DanMossa** [philferriere/dlwin#37]
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
b'C:\\Users\\DanMo\\AppData\\Local\\Temp\\try_flags_jfukzb6c.c:4:19: fatal error: cudnn.h: No such file or directory\r\ncompilation terminated.\r\n'

When I set my `THEANO_FLAGS` to CPU and GPU they worked perfectly, but when I type

`set THEANO_FLAGS=%THEANO_FLAGS_GPU_DNN%`

I get the error about `cudnn.h` is missing.

The thing is, when I go to my sysvariables 

this is what I have for `THEANO_FLAGS_GPU_DNN`

`floatX=float32,device=cuda0,optimizer_including=cudnn,gpuarray.preallocate=0.8,dnn.conv.algo_bwd_filter=deterministic,dnn.conv.algo_bwd_data=deterministic,dnn.include_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include,dnn.library_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64`

And I'm able to clearly see `cudnn.h` file inside

`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include`

Any ideas?

**Comment by apacha** [comment]
Maybe the spaces in your path cause trouble...

**Comment by DanMossa** [comment]
@apacha That's what I was thinking, but I've tried escaping it and I still get the error.

How do you suggest I try escaping the characters?

**Comment by apacha** [comment]
Two ideas, where I would recommend the first: 

- Install Cuda and CuDNN in directories that don't have any spaces as specified in the tutorial (e.g. C:\Toolkits\)
- Define another environment variable and forward-reference that variable, e.g. %CUDA_PATH%

**Comment by DanMossa** [comment]
> Define another environment variable and forward-reference that variable, e.g. %CUDA_PATH%

Worked for me! Thanks :)
