### ISSUE TITLE
Command prompt different

### ISSUE THREAD

**Issue by toqitahamid** [philferriere/dlwin#4]
Your version of command prompt is different than me. How can I get yours?

**Comment by philferriere** [comment]
I use Git Bash:

![gitbashproperties](https://cloud.githubusercontent.com/assets/6441756/19318201/8fc759d4-905c-11e6-889e-2141ceacc58b.png)

To auto-download Git for Windows, go to [https://git-scm.com/download/win](https://git-scm.com/download/win)

**Comment by toqitahamid** [comment]
thanks
