### ISSUE TITLE
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled

### ISSUE THREAD

**Issue by bonifacio123** [philferriere/dlwin#40]
Followed the instructions on Windows 10 with a Nvidia 1080 & 1070 GPU and the four backend checks ran fine. I moved to the next step to validate the Theano install. 

set THEANO_FLAGS=%THEANO_FLAGS_CPU%
and
set THEANO_FLAGS=%THEANO_FLAGS_GPU%

ran fine. However, when I tried:
set THEANO_FLAGS=%THEANO_FLAGS_GPU_DNN%

I get this error
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled

Haven't found a good answer on Google that help me correct this. Any ideas?

Thanks!

THEANO_FLAGS_CPU=
floatX=float32,device=cpu

THEANO_FLAGS_GPU=
floatX=float32,device=cuda0,dnn.enabled=False,gpuarray.preallocate=0.8

THEANO_FLAGS_GPU_DNN=
floatX=float32,device=cuda0,optimizer_including=cudnn,gpuarray.preallocate=0.8,dnn.conv.algo_bwd_filter=deterministic,dnn.conv.algo_bwd_data=deterministic,dnn.include_path=c:/toolkits.win/cuda-8.0.61/include,dnn.library_path=c:/toolkits.win/cuda-8.0.61/lib/x64

**Comment by wpmarinho** [comment]
Sometimes I got that same error. I'm not sure, but I guess that have something to do with this

In Theano docs:
By default, Theano will detect if it can use cuDNN. If so, it will use it. If not, Theano optimizations will not introduce cuDNN ops. So Theano will still work if the user did not introduce them manually.

The recently added Theano flag dnn.enabled allows to change the default behavior to force it or disable it. Older Theano version do not support this flag. To get an error when cuDNN can not be used with them, use this flag: optimizer_including=cudnn.

**Comment by wpmarinho** [comment]
In my case, I solved it by "conda install pygpu" instead of "conda install pygpu==0.6.2". It install  version 0.6.9. This was in notebook with a GeForce 930M. 

I have another machine with a 1080ti but it uses 0.6.2.

So, I dont know for sure what is happening. ;)... 

Phill, Thanks for your excelente tutorial

**Comment by bonifacio123** [comment]
Installing pygpu 0.6.9 fixed the issue. Excellent! Thanks so much for taking the time to help.

**Comment by philferriere** [comment]
Thank you @bonifacio123 and @wpmarinho for reporting & investigating.
I added a note to the `Installing Keras 2.0.5 with Theano 0.9.0 and libgpuarray` section so others can try the same workaround you did.
