### ISSUE TITLE
Not able to import the theano

### ISSUE THREAD

**Issue by coding-work-man** [philferriere/dlwin#42]
I have followed the guides step by step, but not able to import theano. When import theano,I got the following error
 
File "d:\Users\myname\Anaconda3\envs\py36\lib\site-packages\theano\gof\cmodule.py", line 1797, in _try_compile_tmp
    os.remove(exe_path + ".exe")
PermissionError: [WinError 32]

My system info:
1. Win 10 64bit
2. Anconda 3 4.4, Python 3.6

Have tried google but not able to find a solution.

Thanks!

**Comment by apacha** [comment]
Have you tried upgrade to Theano 1.0? Otherwise I suggest you switch to TensorFlow or CNTK, since [Theano is no longer actively developed by MILA](https://github.com/Theano/Theano).
