### ISSUE TITLE
Can anyone be kind and share CUDA 8 for win10 for me?

### ISSUE THREAD

**Issue by egg-west** [philferriere/dlwin#43]
I install the CUDA but there is only 9.0 version on Nvida website,and it doesn't work, at lest in my test.
So could you please share a 8.0 version for win10 ?
Thanks!

**Comment by lzhbrian** [comment]
You can find it on this site: https://developer.nvidia.com/cuda-toolkit-archive

**Comment by egg-west** [comment]
Thank you so much, I was dragwhed for a long while out of this.
