### ISSUE TITLE
  ddeghdgh

### ISSUE THREAD

**Issue by cate5555** [philferriere/dlwin#48]
git branch -m git-branch--m-git-branch--m-main-<BRANCH>-git-fetch-origin-git-branch--u-origin/<BRANCH>-<BRANCH>-<BRANCH>-git-fetch-origin-git-branch--u-origin/<BRANCH>-<BRANCH> <BRANCH>
git fetch origin
git branch -u origin/<BRANCH> <BRANCH>

**Comment by cate5555** [comment]
> git branch -m git-branch--m-git-branch--m-main--git-fetch-origin-git-branch--u-origin/---git-fetch-origin-git-branch--u-origin/-
> git fetch origin
> git branch -u origin/

**Comment by varoll55** [comment]
1.
