### ISSUE TITLE
DEBUG: nvcc STDOUT mod.cu

### ISSUE THREAD

**Issue by toqitahamid** [philferriere/dlwin#5]
I am getting lots of error message like this -

> DEBUG: nvcc STDOUT mod.cu
>    Creating library C:/Users/Prithi/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.12-64/tmppkp9hb/b7b90bf8ebe2fac761d67bb8406d5516.lib and object C:/Users/Prithi/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.12-64/tmppkp9hb/b7b90bf8ebe2fac761d67bb8406d5516.exp

**Comment by philferriere** [comment]
These aren't error messages, just log output.

**Comment by trangnm58** [comment]
I have the same problem. When I train my model, it keeps logging that out and does not show me the training progress as it should. How can I turn this log output off?
