### ISSUE TITLE
TensorFlow -> Theano for Keras

### ISSUE THREAD

**Issue by Litee** [philferriere/dlwin#6]
Hi Phil,

You are my hero - I am finally able to use GPU with Windows 10 thanks to your instruction! I suggest one improvement - Keras should be switched from TensorFlow (default) to Theano in keras.json file (or alternatively via env var) - see https://keras.io/backend/. Without this step Keras GPU example tries to use TF and fails to run if it is not installed.

**Comment by apacha** [comment]
You mean by creating a file ~/.keras/keras.json and adding something like
```
{
    "epsilon": 1e-07,
    "floatx": "float32",
    "image_dim_ordering": "tf",
    "backend": "theano"
}
```
to it?

**Comment by erfannoury** [comment]
You should also change `"image_dim_ordering"` to take value `"th"`.

**Comment by Litee** [comment]
@apacha, @erfannoury, correct.

**Comment by philferriere** [comment]
You're absolutely right. I've added the following to the Keras setup instructions:

Recent builds of Keras can either use Tensorflow or Theano as a backend. At the time of this writing, TensorFlow supports only 64-bit Python 3.5 on Windows. This doesn't work for us, but if you are using Python 3.5, then by all means, feel free to give it a try. By default, we will use Theano as our default backend, using the commands below:

```
$ cp ~/.keras/keras.json ~/.keras/keras.json.bak
$ echo -e '{\n\t"image_dim_ordering": "th",\n\t"epsilon": 1e-07,\n\t"floatx": "float32",\n\t"backend": "theano"\n}' >> ~/.keras/keras_theano.json
$ echo -e '{\n\t"image_dim_ordering": "tf",\n\t"epsilon": 1e-07,\n\t"floatx": "float32",\n\t"backend": "tensorflow"\n}' >> ~/.keras/keras_tensorflow.json
$ cp -f ~/.keras/keras_theano.json ~/.keras/keras.json
```
