### ISSUE TITLE
Couple additions

### ISSUE THREAD

**Issue by alexander-rakhlin** [philferriere/dlwin#7]
Hi Phil,
Nice tutorial. Here is something to add.
1. I noticed MinGW isn't required **at all** as long as libpython installed:
   conda install libpython
2. As of now libpython can not be installed with Python 3.5. You would need 3.4 environment or 2.7

**Comment by apacha** [comment]
Libpython now seems to be available for Anaconda 3 (Python 3.5): https://anaconda.org/anaconda/libpython/files

**Comment by apacha** [comment]
True, MinGW is not required, if you install the following two packages via conda:
```cmd
conda install libpython
conda install m2w64-toolchain
```
I've just tested it with Anaconda3-4.2.0 (Python 3.5). Can someone confirm, that this also holds true for Python 2.7? If so, I will update the tutorial and remove the MinGW installation at all.

**Comment by apacha** [comment]
@philferriere, are you ok with removing MinGW from the tutorial?

**Comment by philferriere** [comment]
@apacha, did you try two non-MingW clean installs (Python 3.5 and Python 2.7) to make sure the entire tutorial can be completed successfully with libpython?

**Comment by philferriere** [comment]
MinGW is now gone from the turorial.
