### ISSUE TITLE
error: GPU device not available

### ISSUE THREAD

**Issue by viksitkumarnigam** [philferriere/dlwin#8]
# Getting the following error, any help would be greatly appreciated!

ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return st                                                                                                                                       atus', 1, 'for cmd', 'nvcc -shared -O3 --use-local-env --cl-version=2008 -Xlinke                                                                                                                                       r /DEBUG -D HAVE_ROUND -m64 -Xcompiler -DCUDA_NDARRAY_CUH=18715462c72ed6afcd7ca5                                                                                                                                       d52813ce90,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD -IC:\toolkits\a                                                                                                                                       naconda2-4.2.0\lib\site-packages\theano-0.8.2-py2.7.egg\theano\sandbox\cud                                                                                                                                       a -IC:\toolkits\anaconda2-4.2.0\lib\site-packages\numpy\core\include -IC:                                                                                                                                       \toolkits\anaconda2-4.2.0\include -IC:\toolkits\anaconda2-4.2.0\lib\site-                                                                                                                                       packages\theano-0.8.2-py2.7.egg\theano\gof -o C:\Users\viksit\AppData\Loc                                                                                                                                       al\Theano\compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_60_Stepping_                                                                                                                                       3_GenuineIntel-2.7.12-64\cuda_ndarray\cuda_ndarray.pyd mod.cu -LC:\toolkits\                                                                                                                                       anaconda2-4.2.0\libs -LC:\toolkits\anaconda2-4.2.0 -lcublas -lpython27 -lcuda                                                                                                                                       rt')
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not availabl                                                                                                                                       e  (error: cuda unavailable)
nvcc fatal   : Value '2008' is not defined for option 'cl-version'

['nvcc', '-shared', '-O3', '--use-local-env', '--cl-version=2008', '-Xlinker', '/DEBUG', '-D HAVE_ROUND', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=18715462c72ed6afcd7ca5d52813ce90,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD', '-IC:\toolkits\anaconda2-4.2.0\lib\site-packages\theano-0.8.2-py2.7.egg\theano\sandbox\cuda', '-IC:\toolkits\anaconda2-4.2.0\lib\site-packages\numpy\core\include', '-IC:\toolkits\anaconda2-4.2.0\include', '-IC:\toolkits\anaconda2-4.2.0\lib\site-packages\theano-0.8.2-py2.7.egg\theano\gof', '-o', 'C:\Users\viksit\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.12-64\cuda_ndarray\cuda_ndarray.pyd', 'mod.cu', '-LC:\toolkits\anaconda2-4.2.0\libs', '-LC:\toolkits\anaconda2-4.2.0', '-lcublas', '-lpython27', '-lcudart']
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
Looping 1000 times took 11.654000 seconds
Result is [ 1.23178029  1.61879337  1.52278066 ...,  2.20771813  2.29967761
  1.62323284]
Used the cpu

**Comment by philferriere** [comment]
Perhaps try the steps discussed here:

http://stackoverflow.com/questions/31108507/installing-theano-on-windows-for-gpu-suspected-nvcc-version-issue

If this link doesn't help, I recommend you google the full error message. This is how I found the link above. There are more of them that seem to discuss the same issue you're facing...

Please share the results of your investigation after you're done. Thanks!

**Comment by apacha** [comment]
Can you please share your hardware specification and the exact versions of the used libraries?

**Comment by philferriere** [comment]
Closing this due to no follow-up from OP.
