### ISSUE TITLE
Validating GPU install with Keras

### ISSUE THREAD

**Issue by bockjo** [philferriere/dlwin#9]
Hi Phil,

thanks for this amazing tutorial. I followed your steps and the Theano GPU validation works perfectly. However, validating GPU install with Keras is a bit strange.

![gpu_install_keras](https://cloud.githubusercontent.com/assets/20744099/19691314/1d980570-9ad4-11e6-8c2a-9076cdc37b01.PNG)

Running the example script, it first executes DEBUG: .... Creating library ... several times (which takes quite a while) before starting the training. Is this normal or have I made a mistake during installation?

Thanks for your help!
Best,
Johannes

**Comment by erfannoury** [comment]
These messages are pretty normal.
When you create a computational graph in Python using Theano, it is then optimized and its optimized code is generated in C and CUDA (in case GPU is selected). These portions of code are then compiled and the main computations are performed using these. So in your case the generated CUDA code is being compiled.

**Comment by apacha** [comment]
As @erfannoury already mentioned, this is normal and has been removed in newer versions of Theano. Still, before starting the training, it will take quite a while to compile the optimized executables used for the training. To avoid that, you might consider using Tensorflow.
